Use core-api via NGINX
streamr-dev/broker pull request #257
Opened 2021-04-28 12:32 UTC by teogeb

Using` http://10.200.10.1` instead of `http://127.0.0.1:8081/streamr-core`

2021-04-28 13:30 UTC, harbu requested changes

2021-04-28 13:30 UTC, harbu commented on configs/docker-1.env.json
> +    "advertisedWsUrl": "ws://127.0.0.1:30315",
Ummm not sure about this change, this should stay as is most likely.

2021-04-28 13:30 UTC, harbu commented on configs/docker-1.env.json
> +      "jsonRpcProvider": "http://127.0.0.1:8545"
Ummm not sure about this change, this should stay as is most likely.

2021-04-28 13:30 UTC, harbu commented on configs/docker-2.env.json
> +    "advertisedWsUrl": "ws://127.0.0.1:30316",
Ummm not sure about this change, this should stay as is most likely.

2021-04-28 13:30 UTC, harbu commented on configs/docker-2.env.json
> +      "jsonRpcProvider": "http://127.0.0.1:8545"
Ummm not sure about this change, this should stay as is most likely.

2021-04-28 13:30 UTC, harbu commented on configs/docker-3.env.json
> +    "advertisedWsUrl": "ws://127.0.0.1:30317",
Ummm not sure about this change, this should stay as is most likely.

2021-04-28 13:30 UTC, harbu commented on configs/docker-3.env.json
> +      "jsonRpcProvider": "http://127.0.0.1:8545"
Ummm not sure about this change, this should stay as is most likely.

2021-04-29 08:39 UTC, harbu approved these changes

2021-04-29 08:57 UTC, kare approved these changes
LGTM

2021-04-29 14:50 UTC, merged